spring:
  datasource:
    url: jdbc:postgresql://ec2-3-208-50-226.compute-1.amazonaws.com:5432/dal3g9ti6un8c1
    username: sdfygsztvmhddv
    password: fd9905b8d281bd6f5773748023ebe35ee5aa2cc91670a2dd4e7a1f4a432e5d00
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: auth-service
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  semaphore:
    max-semaphores: 500
  sensitive-headers: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
management:
  endpoint:
    info:
      enabled: true
    shutdown:
      enabled: true

